<?php
/**
  * Basic Options ACF setup
  *
  * Sets up Developer options for advanced custom fields
  * @since brnm 2.5.4
  * @lastmodified 2.6.1
 **/


if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_basic-options',
		'title' => 'Basic Options',
		'fields' => array (
			array (
				'key' => 'field_5474e243bfe27',
				'label' => 'Message',
				'name' => '',
				'type' => 'message',
				'message' => '<p>These options are available as part of the <strong><em>BRNM Framework</em></strong>. Whether or not they display in your theme depends on whether or not they\'re included in your design.</p>',
			),
			array (
				'key' => 'field_542b5252ca8e1',
				'label' => 'Office',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_542b5278ca8e2',
				'label' => 'Main Phone',
				'name' => 'office_phone_main',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '(555) 123-1234',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b528fca8e3',
				'label' => 'Alternate Phone',
				'name' => 'office_phone_alt',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '(555) 123-4567',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54693d0e8f4fa',
				'label' => 'Fax Phone',
				'name' => 'office_phone_fax',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '(555) 123-4567',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b52a3ca8e4',
				'label' => 'Email',
				'name' => 'office_email',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'name@email.com',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b52b8ca8e5',
				'label' => 'Address',
				'name' => 'office_address',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5469517f7cac3',
				'label' => 'Office Hours',
				'name' => 'office_hours',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5469518f7cac4',
						'label' => 'Day(s)',
						'name' => 'office_day',
						'type' => 'text',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '"i.e. Monday or Mon - Wed"',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_546951a97cac5',
						'label' => 'Time(s)',
						'name' => 'office_time',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '9:00am - 5:00pm',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Hours',
			),
			array (
				'key' => 'field_542b52d2ca8e6',
				'label' => 'Social',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_542b5443ca8e7',
				'label' => 'Facebook',
				'name' => 'social_facebook',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b5450ca8e8',
				'label' => 'Twitter',
				'name' => 'social_twitter',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b5468ca8ea',
				'label' => 'Instagram',
				'name' => 'social_instagram',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b553bca8f1',
				'label' => 'Google+',
				'name' => 'social_google',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b545cca8e9',
				'label' => 'YouTube',
				'name' => 'social_youtube',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b5475ca8eb',
				'label' => 'LinkedIn',
				'name' => 'social_linkedin',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b54cbca8ed',
				'label' => 'Pinterest',
				'name' => 'social_pinterest',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b552dca8f0',
				'label' => 'Tumblr',
				'name' => 'social_tumblr',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b5485ca8ec',
				'label' => 'Yelp',
				'name' => 'social_yelp',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b5515ca8ef',
				'label' => 'Skype',
				'name' => 'social_skype',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b555cca8f2',
				'label' => 'Vimeo',
				'name' => 'social_vimeo',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_542b54dcca8ee',
				'label' => 'RSS',
				'name' => 'social_rss',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5594dc17cb6c3',
				'label' => 'Sharing',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5594dc1dcb6c4',
				'label' => 'Enable Sharing',
				'name' => 'sharing_enable',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'no' => 'No',
					'yes' => 'Yes',
				),
				'default_value' => 'no',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55959e8da59dc',
				'label' => 'Sharing Title (optional)',
				'name' => 'sharing_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5594dc1dcb6c4',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5594dd5dcb6c5',
				'label' => 'Sharable Networks',
				'name' => 'sharing_networks',
				'type' => 'checkbox',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5594dc1dcb6c4',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'facebook' => 'Facebook',
					'twitter' => 'Twitter',
					'google' => 'Google',
					'pinterest' => 'Pinterest',
					'tumblr' => 'Tumblr',
					'linkedin' => 'LinkedIn',
					'envelope' => 'Email',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-general',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => -100,
	));
}