<?php
/**
  * Developer ACF setup
  *
  * Sets up Developer options for advanced custom fields
  * @since brnatermedia 2.4.5
  * @lastmodified brnm 2.6.1
 **/


if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_developer-options',
		'title' => 'Developer Options',
		'fields' => array (
			array (
				'key' => 'field_5469375de9d58',
				'label' => 'Debug',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54693769e9d59',
				'label' => 'Super Admins',
				'name' => 'dev_super_admins',
				'type' => 'user',
				'instructions' => 'Select which admin has developer capability',
				'required' => 1,
				'role' => array (
					0 => 'administrator',
				),
				'field_type' => 'select',
				'allow_null' => 0,
			),
			array (
				'key' => 'field_54693785e9d5a',
				'label' => 'Debug Mode',
				'name' => 'dev_debug_mode',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'off' => 'Off',
					'on' => 'On',
				),
				'default_value' => 'off',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5595bf9e0b82c',
				'label' => 'Maintenance Status',
				'name' => 'dev_maintenance',
				'type' => 'select',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_54693785e9d5a',
							'operator' => '==',
							'value' => 'on',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'off' => 'Off',
					'maintenance_msg' => 'Maintenance Banner',
					'maintenance_pg' => 'Maintenance Page',
					'redirect' => 'Temporary Redirect',
				),
				'default_value' => 'off',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5595c01f0b82d',
				'label' => 'Maintenance Banner Msg',
				'name' => 'dev_maintenance_banner_msg',
				'type' => 'text',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5595bf9e0b82c',
							'operator' => '==',
							'value' => 'maintenance_msg',
						),
						array (
							'field' => 'field_54693785e9d5a',
							'operator' => '==',
							'value' => 'on',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5595cee096fea',
				'label' => 'Show Logo?',
				'name' => 'dev_maintenance_logo_show',
				'type' => 'select',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5595bf9e0b82c',
							'operator' => '==',
							'value' => 'maintenance_pg',
						),
						array (
							'field' => 'field_54693785e9d5a',
							'operator' => '==',
							'value' => 'on',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'no' => 'No',
					'yes' => 'Yes',
				),
				'default_value' => 'no',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5595c8ed24693',
				'label' => 'Maintenance Page Msg',
				'name' => 'dev_maintenance_page_msg',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5595bf9e0b82c',
							'operator' => '==',
							'value' => 'maintenance_pg',
						),
						array (
							'field' => 'field_54693785e9d5a',
							'operator' => '==',
							'value' => 'on',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5595c7fa309f0',
				'label' => 'Splash Image',
				'name' => 'dev_maintenance_splash_image',
				'type' => 'image',
				'instructions' => 'Upload an image 1920 x 1080 in size',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5595bf9e0b82c',
							'operator' => '==',
							'value' => 'maintenance_pg',
						),
						array (
							'field' => 'field_54693785e9d5a',
							'operator' => '==',
							'value' => 'on',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5595c0c70b82e',
				'label' => 'Redirect To',
				'name' => 'dev_maintenance_redirect',
				'type' => 'text',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5595bf9e0b82c',
							'operator' => '==',
							'value' => 'redirect',
						),
						array (
							'field' => 'field_54693785e9d5a',
							'operator' => '==',
							'value' => 'on',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5595bf800b82b',
				'label' => 'Credits',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_546937a6e9d5b',
				'label' => 'White label project?',
				'name' => 'dev_white_label',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_546937c2e9d5c',
				'label' => 'Agency Name',
				'name' => 'dev_wl_agency_name',
				'type' => 'text',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_546937a6e9d5b',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_546937d7e9d5d',
				'label' => 'Agency Link',
				'name' => 'dev_wl_agency_link',
				'type' => 'text',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_546937a6e9d5b',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5469380be9d5e',
				'label' => 'Agency Support Link',
				'name' => 'dev_wl_agency_support',
				'type' => 'text',
				'instructions' => 'A website or email link where the client can receive support.',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_546937a6e9d5b',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'http://',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54693844e9d5f',
				'label' => 'Theme Setup',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5474e60bf9dc0',
				'label' => 'Client Name',
				'name' => 'clientname',
				'type' => 'text',
				'instructions' => 'Creates the custom acf options page. <em style="color: red;">Warning: changing this will break the page and unhook the options set to it. </em>',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5469384ee9d60',
				'label' => 'Theme Preset',
				'name' => 'dev_theme_presets',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'blog' => 'Blog',
					'site' => 'Website',
					'blogsite' => 'Website + Blog',
					'full' => 'All admin menus except Developer',
				),
				'default_value' => 'site',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5469389be9d61',
				'label' => 'Mobile-friendly Options',
				'name' => 'dev_mobile_friendly',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'no' => 'Not mobile friendly',
					'yes' => 'Mobile-friendly',
				),
				'default_value' => 'no',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5474df8d169ec',
				'label' => 'Hero Media',
				'name' => 'media_type',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'layerslider' => 'LayerSlider',
					'owlcarousel' => 'Owl Carousel',
					'mosaic' => 'Mosaic Styles',
					'static' => 'Static Image',
					'none' => 'No Media',
				),
				'default_value' => 'none',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_546938dae9d62',
				'label' => 'Enable Google Analytics',
				'name' => 'dev_ga',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_546938ece9d63',
				'label' => 'Google Analytics Code',
				'name' => 'dev_ga_use',
				'type' => 'textarea',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_546938dae9d62',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_54693918e9d64',
				'label' => 'Enable Event Tracking',
				'name' => 'dev_ga_event_tracking',
				'type' => 'true_false',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_546938dae9d62',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5469392ee9d65',
				'label' => 'Login',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5469393ae9d66',
				'label' => 'Logo',
				'name' => 'login_logo',
				'type' => 'image',
				'save_format' => 'id',
				'preview_size' => 'logo',
				'library' => 'all',
			),
			array (
				'key' => 'field_5469394ee9d67',
				'label' => 'Login Background',
				'name' => 'login_bg_type',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'color' => 'Background Color',
					'image' => 'Background Image',
				),
				'default_value' => 'color',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_54693978e9d68',
				'label' => 'Background Color',
				'name' => 'login_color',
				'type' => 'color_picker',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5469394ee9d67',
							'operator' => '==',
							'value' => 'color',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
			),
			array (
				'key' => 'field_54693990e9d69',
				'label' => 'Background Image',
				'name' => 'login_image',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5469394ee9d67',
							'operator' => '==',
							'value' => 'image',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'id',
				'preview_size' => 'logo',
				'library' => 'all',
			),
			array (
				'key' => 'field_546939bce9d6a',
				'label' => 'Background Position',
				'name' => 'login_image_position',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5469394ee9d67',
							'operator' => '==',
							'value' => 'image',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'center' => 'center',
					'left_top' => 'top-left',
					'left_bottom' => 'bottom-left',
					'right_top' => 'top-right',
					'right_bottom' => 'bottom-right',
				),
				'default_value' => 'left_bottom',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-developer',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => -100,
	));
}
